### ISSUE TITLE
JSON schema draft version?

### ISSUE THREAD

**Issue by mesopelagique** [AdrienCagniant/4DPop-JSON-Validator#2]
In 4d doc I read schema draft 4
https://doc.4d.com/4Dv18/4D/18/JSON-Validate.301-4505350.en.html

but I see in resource draft 6
https://github.com/AdrienCagniant/4DPop-JSON-Validator/blob/master/Resources/json-schema.json

Is there a 4D update with draft4? or we must embed in this component draft 4 instead

**Comment by vdelachaux** [comment]
For information, the schemas, that I found into the 4D (main) Resources folder are all draft 4. ie: formsSchema.json, JSONSchemas/mobileSessionSchema.json

**Comment by AdrienCagniant** [comment]
hi,
I've commited the schema draft 4 following your comment. 

https://github.com/AdrienCagniant/4DPop-JSON-Validator/commit/e6133b4eb644408fab437b62faaae1a1bddb24ec

Thanks for your time :)

**Comment by AdrienCagniant** [comment]
commit 470e88a is fixing the issue
